name: ultraSEM Tests
on: [push]
jobs:
  ultraSEM-test:
    name: Run ultraSEM tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Install MATLAB
        uses: matlab-actions/setup-matlab@v0
      - name: Run commands
        uses: matlab-actions/run-command@v0
        with:
          command: addpath('ultraSEM'); results = ultraSEM.test; assert(all([results{:,2}] > 0))
